### ISSUE TITLE
`foo.bar-baz` is broken

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#12]
`foo.bar` works, but `foo.bar-baz` is compiled to `foo.bar_baz`

For example, 

```
> (define-global system (require 'system))
(write-file: function write: function read-file: function argv: ("/Users/vagrant/.sol/lib/lumen/sctb/bin/lumen.lua" "luajit") path-join: function file-exists?: function path-separator: "/" exit: function get-environment-variable: function)

> system.argv
("/Users/vagrant/.sol/lib/lumen/sctb/bin/lumen.lua" "luajit")

> system.write-file

> (get system 'write-file)
function
```

I believe the correct fix is to add `define-syntax` to Lumen's compiler, since `foo.bar-baz` is shorthand for `(get foo 'bar-baz)`.

This would also enable applications to add their own syntax, e.g. `~foo` expanding to `(complement foo)`, which is necessary for my purposes.

**Comment by sctb** [comment]
There is full reader extensibility in Lumen, and `foo.bar-baz` was in fact implemented in the reader function for atoms, before it was recently removed. `(get reader 'read-table)` is available for modification (as of d646a4b89), and the the reader function for atoms is at `(get read-table "")`.

**Comment by laarc** [comment]
Certainly.  What I meant to highlight was,

```
> ((get (require 'reader) 'read-string) "(foo.bar)")
("foo.bar")
```

is correct behavior.  It would be incorrect for this to yield `("get" "foo" ("quote" "bar"))` for example.

It seems the job of the compiler (specifically `compiler.expand`) to translate `foo.bar` into `(get foo 'bar)`.

For instance, imagine we implement a dialect of Lisp using Lumen.  We would like to expose a `read` function to it such that the dialect can run `(eval (read "(+ 1 2)"))` which yields `3`.  What would you say would be the correct way to accomplish this?  Should I re-use Lumen's reader, or write a custom `read` function which is then exposed to the language?

**Comment by sctb** [comment]
I don't believe it's the compiler's job to translate `foo.bar`, because macros need to be able to operate on s-expressions. That is, all of the syntax needs to be squeezed out by the time the reader is done so that macros can understand the meaning of expressions. 

There are a few possibilities for building dialects on top of Lumen: 
1. Manipulate the existing `read-table` and call Lumen's `read`
2. Implement a separate reader
3. Call Lumen's reader first, then process its output further

A mixture of these approaches also seems possible. For what it's worth, the Arc compiler generally does the equivalent of #3.

**Comment by laarc** [comment]
Ok, PR #14 extends Lumen's reader to convert `foo.bar` into `(get foo 'bar)`.

It seems like a good idea to merge it into mainline Lumen rather than leave it up to Lumen's users, especially because "." recently became a `valid-code?`

What do you think?
