### ISSUE TITLE
javascript interoperability

### ISSUE THREAD

**Issue by mjobuda** [sctb/lumen#223]
How hard would it be to be able to execute JS functions? Let's say for sake of simplicity on node.
I've seen in the source code stuff like (get console 'log),
but wasn't able to achieve much more. It was possible to do (require 'fs) and the whole list of functions of this module pops up, but I wasn't able to do much more

**Comment by sctb** [comment]
I think you're nearly there! Lumen functions are JavaScript functions, so you can invoke them in the same way. The biggest hurdle is the syntax, because JavaScript makes things like `require('fs').mkdir(...)` easy to write, but in Lumen it would look pretty awkward: `((get (require 'fs) 'mkdir) ...)`. 

I think the convention in Lumen is to bind function objects to variables before using them. This file in the source code might be the most helpful to consult: https://github.com/sctb/lumen/blob/master/system.l. At the REPL, you could go further with your `(require 'fs)` by doing something like:

```
> (define fs (require 'fs))
...
> (define slurp-file (get fs 'readFileSync))
...
> (slurp-file "my-file.txt" 'utf8)
```

**Comment by sctb** [comment]
Closing.
