### ISSUE TITLE
Add overall project description

### ISSUE THREAD

**Issue by maximvl** [sctb/lumen#33]
Hi! As a Lisp fan I'm glad to see new implementations appear. But lumen's README says nothing about the project itself, it only contains basic examples. 

It would be nice if you add things like project goal (e.g. experimental implementation or problem-oriented solution), language features list (lisp1/lisp2, special variables, object system, condition-restarts, reader-macros, etc), features you have plans for, commons and differences with existing wide-spreaded lisps (CL, Scheme), and with similar projects like https://github.com/davazp/jscl .

**Comment by sctb** [comment]
Thanks for the suggestion! The additional description that I've added is probably not as comprehensive as you were hoping for, but I might expand on it later.

**Comment by laarc** [comment]
Hello.

The project's authors are extremely busy.  They care about Lumen's success, but you have to understand that they wrote Lumen primarily for themselves, not for the world.  That's partly why it turned out so well, and why Lumen is so effective.

I won't speak for the authors.  Nor will I pretend to be some kind of Lumen evangelist or anybody special at all.  I'm just a person who wanted to design a powerful Lisp, then noticed Lumen is the perfect runtime for it.

Here's a glimpse of what I can do in my dialect of Lisp built atop Lumen:

I'm writing an autoindenter for Lisp, and I suspected the Parinfer npm library might help.  The usual way to explore a Node library is to use e.g. https://tonicdev.com/ (which is fantastic).  Nowadays, though, I just use my dialect, which is just a small set of macros over Lumen to make it slightly easier for REPL work.

Testing out Parinfer was as simple as starting from the Node instructions at https://github.com/shaunlebron/parinfer/tree/master/lib/npm-publish

```
  $ wget https://github.com/shaunlebron/parinfer/releases/download/0.2.3/parinfer.js
  $ LUMEN_HOST=node sudoarc
```

```
  > (lib parinfer)
  (indentMode: function Yh(a,b){var c;c=Wh(b);c=Pf(kc([zh,...

  > parinfer
  (indentMode: function Yh(a,b){var c;c=Wh(b);c=Pf(kc([zh,...

  > (map [at _ 0] (kvs parinfer))
  ("indentMode" "indentModeChange" "parenMode")

  > (def pr/paren (str) (let x (parinfer.parenMode str) (prn x.text)))

  > (def pr/indent (str) (let x (parinfer.indentMode str) (prn x.text)))

  > (prn "(if t (foo)\n(+ 1\n2 3)))")
  (if t (foo)
  (+ 1
  2 3)))

  > (pr/paren "(if t (foo)\n(+ 1\n2 3)))")
  (if t (foo)
   (+ 1
    2 3))

  > (pr/indent "(if t (foo)\n(+ 1\n2 3)))")
  (if t (foo))
  (+ 1)
  2 3
```

I very quickly got an idea of what Parinfer's functionality was doing, and what it offers me.  And Parinfer is Javascript.  The power of Lumen  is that it's very easy to interface with Node, Lua, or C via LuaJIT's FFI:  https://github.com/sctb/motor/blob/611e0833d5f93fc21ff2e6d6c41884497dddff71/motor.l#L6-L60  Suffice to say, it's pretty awesome for exploratory programming.

So, welcome!  I encourage you to give Lumen a serious go, and to tell me about any rough edges you run into.  I'll iron them out.

It's been one surprise after another, using Lumen daily for about three months now.  (I would have left long ago if it wasn't effective; when I say "I use it daily," I mean out of necessity rather than happiness.)

I am fairly certain that the world is about to notice the good idea that Lumen embodies, and that Lumen's popularity may explode.  If you're looking for the most effortless way to write JS, you've found it, for example.  Jump on in and enjoy the ride -- contact me if you have any questions or just want to chat with a user.

If you happen to be an Emacs user, check out Numen:  http://github.com/gruseom/numen

It's a debugger / REPL for Lumen.  Sort of tough to set up, but I've been meaning to put up a tutorial somewhere.

(Lumen may benefit from creating a github Wiki, though.)

There's nowhere for a Lumen community to gather right now, but that may be fixable by setting up e.g. a #lumen https://demo.rocket.chat channel.  (Rocket is open-source Slack.)  But there are a wide variety of things to do to help out Lumen's growth, and they're all a lot of fun.

Have fun! :)
